### ISSUE TITLE
mount error

### ISSUE THREAD

**Issue by ifForeverlove** [omnirom/android_system_vold#3]
when I got the following log,the usb device couldn't mount until I reboot .

I wonder whether there is there is a way to solve this problem？

01-01 14:00:58.600207  2051  2103 V vold    : ----------------
01-01 14:00:58.600270  2051  2103 V vold    : handleBlockEvent with action 1
01-01 14:00:58.600306  2051  2103 D NetlinkEvent: NL param 'DEVPATH=/devices/platform/11271000.usb/11270000.xhci/usb1/1-1/1-1:1.0/host0/target0:0:0/0:0:0:0/block/sdb/sdb1'
01-01 14:00:58.600341  2051  2103 D NetlinkEvent: NL param 'MAJOR=8'
01-01 14:00:58.600367  2051  2103 D NetlinkEvent: NL param 'MINOR=17'
01-01 14:00:58.600394  2051  2103 D NetlinkEvent: NL param 'DEVNAME=sdb1'
01-01 14:00:58.600420  2051  2103 D NetlinkEvent: NL param 'DEVTYPE=partition'
01-01 14:00:58.600445  2051  2103 D NetlinkEvent: NL param 'PARTN=1'
01-01 14:00:58.607972  2682  2682 D StorageNotification: Notifying about public volume: VolumeInfo{public:8,17}:
01-01 14:00:58.607972  2682  2682 D StorageNotification:     type=PUBLIC diskId=disk:8,16 partGuid= mountFlags=VISIBLE mountUserId=0 
01-01 14:00:58.607972  2682  2682 D StorageNotification:     state=UNMOUNTABLE 
01-01 14:00:58.607972  2682  2682 D StorageNotification:     fsType=vfat fsUuid=1C09-81EA fsLabel=KINGSTON 
01-01 14:00:58.607972  2682  2682 D StorageNotification:     path=/storage/udisk1 internalPath=/mnt/media_rw/udisk1 
01-01 14:00:58.611066  2563  2658 E StorageManagerService: 
01-01 14:00:58.611066  2563  2658 E StorageManagerService: android.os.ServiceSpecificException:  (code -1)
01-01 14:00:58.611066  2563  2658 E StorageManagerService: 	at android.os.Parcel.createException(Parcel.java:1956)
01-01 14:00:58.611066  2563  2658 E StorageManagerService: 	at android.os.Parcel.readException(Parcel.java:1910)
01-01 14:00:58.611066  2563  2658 E StorageManagerService: 	at android.os.Parcel.readException(Parcel.java:1860)
01-01 14:00:58.611066  2563  2658 E StorageManagerService: 	at android.os.IVold$Stub$Proxy.mount(IVold.java:756)
01-01 14:00:58.611066  2563  2658 E StorageManagerService: 	at com.android.server.StorageManagerService$StorageManagerServiceHandler.handleMessage(StorageManagerService.java:621)
01-01 14:00:58.611066  2563  2658 E StorageManagerService: 	at android.os.Handler.dispatchMessage(Handler.java:106)
01-01 14:00:58.611066  2563  2658 E StorageManagerService: 	at android.os.Looper.loop(Looper.java:193)
01-01 14:00:58.611066  2563  2658 E StorageManagerService: 	at android.os.HandlerThread.run(HandlerThread.java:65)
01-01 14:00:58.613807  2563  2658 D StorageManagerService: Volume public:8,17 broadcasting removed to UserHandle{0}
01-01 14:00:58.616069  2051  2102 V vold    : /system/bin/blkid
01-01 14:00:58.616268  2051  2102 V vold    :     -c
01-01 14:00:58.616306  2051  2102 V vold    :     /dev/null
01-01 14:00:58.616340  2051  2102 V vold    :     -s
01-01 14:00:58.616374  2051  2102 V vold    :     TYPE
01-01 14:00:58.616407  2051  2102 V vold    :     -s
01-01 14:00:58.616440  2051  2102 V vold    :     UUID
01-01 14:00:58.616627  2051  2102 V vold    :     -s
01-01 14:00:58.616669  2051  2102 V vold    :     LABEL
01-01 14:00:58.616708  2051  2102 V vold    :     /dev/block/vold/public:8,17
01-01 14:00:58.623181  2682  2682 D StorageNotification: Notifying about public volume: VolumeInfo{public:8,17}:
01-01 14:00:58.623181  2682  2682 D StorageNotification:     type=PUBLIC diskId=disk:8,16 partGuid= mountFlags=VISIBLE mountUserId=0 
01-01 14:00:58.623181  2682  2682 D StorageNotification:     state=CHECKING 
01-01 14:00:58.623181  2682  2682 D StorageNotification:     fsType=vfat fsUuid=1C09-81EA fsLabel=KINGSTON 
01-01 14:00:58.623181  2682  2682 D StorageNotification:     path=/storage/udisk1 internalPath=/mnt/media_rw/udisk1 
01-01 14:00:58.665897  2051  2102 V vold    : /dev/block/vold/public:8,17: LABEL="KINGSTON" UUID="1C09-81EA" TYPE="vfat" 
01-01 14:00:58.666007  2051  2102 V vold    : 
01-01 14:00:58.666942  2051  2102 E cutils  : Failed to chown(/mnt/media_rw/udisk1, 0, 0): Operation not permitted
01-01 14:00:58.667053  2051  2102 E vold    : public:8,17 failed to create mount points: Operation not permitted
01-01 14:00:58.667692  2563  2658 E StorageManagerService: 
01-01 14:00:58.667692  2563  2658 E StorageManagerService: android.os.ServiceSpecificException:  (code -1)
01-01 14:00:58.667692  2563  2658 E StorageManagerService: 	at android.os.Parcel.createException(Parcel.java:1956)
01-01 14:00:58.667692  2563  2658 E StorageManagerService: 	at android.os.Parcel.readException(Parcel.java:1910)
01-01 14:00:58.667692  2563  2658 E StorageManagerService: 	at android.os.Parcel.readException(Parcel.java:1860)
01-01 14:00:58.667692  2563  2658 E StorageManagerService: 	at android.os.IVold$Stub$Proxy.mount(IVold.java:756)
01-01 14:00:58.667692  2563  2658 E StorageManagerService: 	at com.android.server.StorageManagerService$StorageManagerServiceHandler.handleMessage(StorageManagerService.java:621)
01-01 14:00:58.667692  2563  2658 E StorageManagerService: 	at android.os.Handler.dispatchMessage(Handler.java:106)
01-01 14:00:58.667692  2563  2658 E StorageManagerService: 	at android.os.Looper.loop(Looper.java:193)
01-01 14:00:58.667692  2563  2658 E StorageManagerService: 	at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by ifForeverlove** [comment]
@darkobas
